# Generated by Django 4.0 on 2021-12-17 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='car_make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='model',
            new_name='car_model',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rates_number',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rates_sum',
        ),
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('car_make', 'car_model')},
        ),
    ]
