# Generated by Django 4.0 on 2021-12-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_rating_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='car',
        ),
        migrations.AddField(
            model_name='rating',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
            preserve_default=False,
        ),
    ]
