# Generated by Django 4.0 on 2021-12-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_rating_car_rating_car_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model')},
        ),
    ]
